# Generated by Django 4.2.11 on 2024-04-21 18:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.UUIDField(default='9245fd26277348bf831f9c3478d05c72', primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default='60a0496b994f4fb984da3b506af2c39f', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField()),
                ('name', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField()),
                ('name', models.TextField()),
                ('score', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('source', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('chemicalTranslation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chemicaltranslation')),
            ],
        ),
        migrations.AddField(
            model_name='chemical',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product'),
        ),
    ]
